CREATE TABLE users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  address VARCHAR(255),
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255),
  is_deleted TINYINT(1) DEFAULT FALSE
);