@startuml
'https://plantuml.com/sequence-diagram

    note as N1
        <size:15>The diagram demonstrates only some of
        <size:15>the exceptions created in the application to
        <size:15>show the relationship between them.
        <size:15>The other exceptions are created in a similar way.<size:18>
    end note

    abstract class ApiException <<RuntimeException>> {
        - status: HttpStatus
        - statusCode: Integer

        + ApiException(String message, HttpStatus status)
        + getStatus(): HttpStatus
        + getStatusCode(): Integer

        {abstract}
        + setStatus(HttpStatus status): void
        + setStatusCode(Integer statusCode): void
    }

    exception BadRequestException {
        <<extends>> ApiException
        + BadRequestException()
        + BadRequestException(String message)
    }

    exception IllegalArgumentApiException {
        <<extends>> ApiException
        + IllegalArgumentApiException()
    }

    exception InternalServerErrorException {
        <<extends>> ApiException
        + InternalServerErrorException()
    }

    exception NoSuchElementException {
        <<extends>> ApiException
        + NoSuchElementException()
    }

    exception AccessDeniedException {
        <<extends>> ApiException
        + AccessDeniedException()
    }

    ApiException <|-- BadRequestException
    ApiException <|-- IllegalArgumentApiException
    ApiException <|-- InternalServerErrorException
    ApiException <|-- NoSuchElementException

    ApiException <|-- AccessDeniedException


@enduml