export enum PagesEnum {
  Home = '/',
  Contact = '/contact',
  Login = '/login',
  Register = '/register',
  Logout = '/logout',
  Quizzes = '/quizzes',
  Courses = '/courses',
  CoursesCreate = '/courses/create',
  SingleCourse = '/courses/:id',
  Blog = '/blog',
  BlogCreate = '/blog/create',
  SingleBlog = '/blog/:id',
  Admin = '/admin',
  NotFound = '/not-found',
}
